# Use official Python base image
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .

RUN pip install -r requirements.txt

# Copy producer code
COPY data_generator/ .

# Default command
CMD ["python", "-u", "ride_event_producer.py"]